// Turkish School Demo Data — Comprehensive Single Source of Truth for Oxonom Edu
export interface SchoolStudent {
  id: number
  studentNo: string
  tcNo: string
  name: string
  first_name: string
  last_name: string
  email: string
  username: string
  avatar_image: string
  gender: 'Kız' | 'Erkek'
  birthDate: string
  bloodType: string
  address: string
  classroomId: number
  classroomName: string
  mentorTeacher: string
  status: 'active' | 'frozen' | 'graduated'
  parentName: string
  parentPhone: string
  parentRelation: string
  parentOccupation: string
  emergencyContact: string
  emergencyPhone: string
  enrollmentDate: string
  gpa: number
  attendanceRate: number
  excusedDays: number
  unexcusedDays: number
  assignmentsDone: number
  assignmentsTotal: number
  notes: string
  disciplineStatus: string
}

export const TURKISH_STUDENTS: SchoolStudent[] = [
  {
    id: 51,
    studentNo: '2026-101',
    tcNo: '10928374652',
    name: 'Ali Demir',
    first_name: 'Ali',
    last_name: 'Demir',
    email: 'ogrenci@oxonom.com',
    username: 'ogrenci',
    avatar_image: '',
    gender: 'Erkek',
    birthDate: '14.03.2010 (16 Yaşında)',
    bloodType: 'A Rh+',
    address: 'Atatürk Mah. Karanfil Cad. No:14/5 Çankaya / Ankara',
    classroomId: 6,
    classroomName: '10-A Fen ve Matematik Şubesi',
    mentorTeacher: 'Ahmet Yılmaz (Matematik)',
    status: 'active',
    parentName: 'Mehmet Demir',
    parentPhone: '+90 532 111 2233',
    parentRelation: 'Baba',
    parentOccupation: 'Makine Mühendisi',
    emergencyContact: 'Mehmet Demir (Baba)',
    emergencyPhone: '+90 532 111 2233',
    enrollmentDate: '15.09.2025',
    gpa: 92.5,
    attendanceRate: 98,
    excusedDays: 1,
    unexcusedDays: 0,
    assignmentsDone: 18,
    assignmentsTotal: 18,
    notes: 'Matematik, Fizik ve Akıllı Tahta projelerinde yüksek başarı. 10-A Sınıf Temsilcisi.',
    disciplineStatus: 'Temiz Sicil — Onur Kurulu Takdir Belgesi mevcuttur.',
  },
  {
    id: 44,
    studentNo: '2026-102',
    tcNo: '28475910293',
    name: 'Can Demir',
    first_name: 'Can',
    last_name: 'Demir',
    email: 'can_student@oxonom.com',
    username: 'can_student',
    avatar_image: '',
    gender: 'Erkek',
    birthDate: '22.07.2010 (16 Yaşında)',
    bloodType: '0 Rh+',
    address: 'Bahçelievler Mah. 7. Cadde No:32/8 Çankaya / Ankara',
    classroomId: 6,
    classroomName: '10-A Fen ve Matematik Şubesi',
    mentorTeacher: 'Ahmet Yılmaz (Matematik)',
    status: 'active',
    parentName: 'Zeynep Demir',
    parentPhone: '+90 532 222 3344',
    parentRelation: 'Anne',
    parentOccupation: 'Mimar',
    emergencyContact: 'Zeynep Demir (Anne)',
    emergencyPhone: '+90 532 222 3344',
    enrollmentDate: '15.09.2025',
    gpa: 88.0,
    attendanceRate: 95,
    excusedDays: 2,
    unexcusedDays: 0,
    assignmentsDone: 17,
    assignmentsTotal: 18,
    notes: 'Fen laboratuvarı deneylerinde ve grup çalışmalarında aktif.',
    disciplineStatus: 'Temiz Sicil',
  },
  {
    id: 3,
    studentNo: '2026-103',
    tcNo: '39485710294',
    name: 'Selin Kurt',
    first_name: 'Selin',
    last_name: 'Kurt',
    email: 'student@oxonom.com',
    username: 'selin_kurt',
    avatar_image: '',
    gender: 'Kız',
    birthDate: '05.11.2010 (16 Yaşında)',
    bloodType: 'B Rh+',
    address: 'Kavaklıdere Mah. Tunalı Hilmi Cad. No:54/12 Çankaya / Ankara',
    classroomId: 6,
    classroomName: '10-A Fen ve Matematik Şubesi',
    mentorTeacher: 'Ahmet Yılmaz (Matematik)',
    status: 'active',
    parentName: 'Kemal Kurt',
    parentPhone: '+90 532 333 4455',
    parentRelation: 'Baba',
    parentOccupation: 'Avukat',
    emergencyContact: 'Kemal Kurt (Baba)',
    emergencyPhone: '+90 532 333 4455',
    enrollmentDate: '15.09.2025',
    gpa: 94.2,
    attendanceRate: 99,
    excusedDays: 0,
    unexcusedDays: 0,
    assignmentsDone: 18,
    assignmentsTotal: 18,
    notes: 'Dönem birinciliği adayı. Edebiyat ve Biyoloji derslerinde üstün başarı.',
    disciplineStatus: 'Temiz Sicil — Üstün Başarı Belgesi',
  },
  {
    id: 46,
    studentNo: '2026-104',
    tcNo: '48392019485',
    name: 'Ali Kaya',
    first_name: 'Ali',
    last_name: 'Kaya',
    email: 'ogrenci_ali@oxonom.com',
    username: 'ali_kaya',
    avatar_image: '',
    gender: 'Erkek',
    birthDate: '18.01.2010 (16 Yaşında)',
    bloodType: 'AB Rh+',
    address: 'Emek Mah. Bişkek Cad. No:21/4 Çankaya / Ankara',
    classroomId: 6,
    classroomName: '10-A Fen ve Matematik Şubesi',
    mentorTeacher: 'Ahmet Yılmaz (Matematik)',
    status: 'active',
    parentName: 'Fatma Kaya',
    parentPhone: '+90 532 444 5566',
    parentRelation: 'Anne',
    parentOccupation: 'Doktor',
    emergencyContact: 'Fatma Kaya (Anne)',
    emergencyPhone: '+90 532 444 5566',
    enrollmentDate: '15.09.2025',
    gpa: 86.5,
    attendanceRate: 94,
    excusedDays: 3,
    unexcusedDays: 0,
    assignmentsDone: 16,
    assignmentsTotal: 18,
    notes: 'Robotik ve Kodlama kulübü üyesi.',
    disciplineStatus: 'Temiz Sicil',
  },
  {
    id: 47,
    studentNo: '2026-105',
    tcNo: '58493029485',
    name: 'Ayşe Yılmaz',
    first_name: 'Ayşe',
    last_name: 'Yılmaz',
    email: 'ayse_student@oxonom.com',
    username: 'ayse_yilmaz',
    avatar_image: '',
    gender: 'Kız',
    birthDate: '30.08.2010 (16 Yaşında)',
    bloodType: '0 Rh-',
    address: 'Ayrancı Mah. Güvenlik Cad. No:40/2 Çankaya / Ankara',
    classroomId: 6,
    classroomName: '10-A Fen ve Matematik Şubesi',
    mentorTeacher: 'Ahmet Yılmaz (Matematik)',
    status: 'active',
    parentName: 'Mustafa Yılmaz',
    parentPhone: '+90 532 555 6677',
    parentRelation: 'Baba',
    parentOccupation: 'Öğretim Görevlisi',
    emergencyContact: 'Mustafa Yılmaz (Baba)',
    emergencyPhone: '+90 532 555 6677',
    enrollmentDate: '15.09.2025',
    gpa: 90.8,
    attendanceRate: 97,
    excusedDays: 1,
    unexcusedDays: 0,
    assignmentsDone: 18,
    assignmentsTotal: 18,
    notes: 'TÜBİTAK Matematik Olimpiyatları takımında okul temsilcisi.',
    disciplineStatus: 'Temiz Sicil',
  },
  {
    id: 45,
    studentNo: '2026-106',
    tcNo: '67584930291',
    name: 'Ahmet Can',
    first_name: 'Ahmet',
    last_name: 'Can',
    email: 'ahmet_can@oxonom.com',
    username: 'ahmet_can',
    avatar_image: '',
    gender: 'Erkek',
    birthDate: '12.12.2010 (16 Yaşında)',
    bloodType: 'A Rh-',
    address: 'Gaziosmanpaşa Mah. Arjantin Cad. No:19/7 Çankaya / Ankara',
    classroomId: 6,
    classroomName: '10-A Fen ve Matematik Şubesi',
    mentorTeacher: 'Ahmet Yılmaz (Matematik)',
    status: 'active',
    parentName: 'Emine Can',
    parentPhone: '+90 532 666 7788',
    parentRelation: 'Anne',
    parentOccupation: 'Eczacı',
    emergencyContact: 'Emine Can (Anne)',
    emergencyPhone: '+90 532 666 7788',
    enrollmentDate: '15.09.2025',
    gpa: 87.4,
    attendanceRate: 93,
    excusedDays: 2,
    unexcusedDays: 1,
    assignmentsDone: 16,
    assignmentsTotal: 18,
    notes: 'Okul basketbol ve satranç takımında aktif sporcu.',
    disciplineStatus: 'Temiz Sicil',
  },
]

export const TURKISH_TEACHERS = [
  {
    id: 2,
    name: 'Ahmet Yılmaz (Öğretmen)',
    first_name: 'Ahmet',
    last_name: 'Yılmaz',
    tcNo: '29182736450',
    email: 'ogretmen@oxonom.com',
    username: 'ogretmen',
    branch: 'Matematik & Geometri',
    phone: '+90 532 999 8877',
    university: 'ODTÜ Matematik Öğretmenliği',
    graduationYear: '2016',
    birthDate: '12.05.1991 (35 Yaşında)',
    address: 'Çankaya Mah. Barış Cad. No:8/3 Çankaya / Ankara',
    emergencyContact: 'Gül Yılmaz (Eşi)',
    emergencyPhone: '+90 532 111 4455',
    isClassMentor: true,
    mentorClass: '10-A',
    assignedClasses: ['10-A', '11-B', '9-C'],
    status: 'active',
    workingHours: '08:30 - 16:30 (Pazartesi - Cuma)',
    weeklyHours: 24,
    employmentType: 'Kadrolu',
  },
  {
    id: 301,
    name: 'Zeynep Kaya',
    first_name: 'Zeynep',
    last_name: 'Kaya',
    tcNo: '38291049582',
    email: 'zeynep.kaya@oxonom.com',
    username: 'zeynep_kaya',
    branch: 'Fizik & Fen Bilimleri',
    phone: '+90 532 888 7766',
    university: 'Hacettepe Fizik Öğretmenliği',
    graduationYear: '2018',
    birthDate: '19.09.1993 (33 Yaşında)',
    address: 'Bilkent Mah. Üniversite Cad. No:12 Çankaya / Ankara',
    emergencyContact: 'Murat Kaya (Kardeşi)',
    emergencyPhone: '+90 532 222 6677',
    isClassMentor: false,
    assignedClasses: ['10-A', '11-B'],
    status: 'active',
    workingHours: '08:30 - 16:30',
    weeklyHours: 20,
    employmentType: 'Kadrolu',
  },
  {
    id: 302,
    name: 'Burak Yıldız',
    first_name: 'Burak',
    last_name: 'Yıldız',
    tcNo: '49201948572',
    email: 'burak.yildiz@oxonom.com',
    username: 'burak_yildiz',
    branch: 'Türk Dili ve Edebiyatı',
    phone: '+90 532 777 6655',
    university: 'Ankara Üniversitesi Türk Dili ve Edebiyatı',
    graduationYear: '2015',
    birthDate: '04.02.1990 (36 Yaşında)',
    address: 'GOP Mah. Kuleli Cad. No:5 Çankaya / Ankara',
    emergencyContact: 'Banu Yıldız (Eşi)',
    emergencyPhone: '+90 532 333 8899',
    isClassMentor: true,
    mentorClass: '9-C',
    assignedClasses: ['10-A', '9-C'],
    status: 'active',
    workingHours: '08:30 - 16:30',
    weeklyHours: 22,
    employmentType: 'Kadrolu',
  },
]

export const TURKISH_COMMUNITIES = [
  {
    id: 1,
    community_uuid: 'comm_10a_sinif_forumu',
    org_id: 2,
    name: '10-A Sınıfı Forumu & Ders Tartışmaları',
    description: '10-A sınıfı öğrencileri ve öğretmenleri için ders soru-cevap, sınav hazırlık ve proje paylaşım alanı.',
    public: true,
    thumbnail_image: null,
    creation_date: '2026-09-30 10:00:00',
    update_date: '2026-10-01 10:00:00',
  },
  {
    id: 2,
    community_uuid: 'comm_10a_veli_bilgilendirme',
    org_id: 2,
    name: '10-A Veli Bilgilendirme ve Danışma Panosu',
    description: 'Değerli velilerimiz için okul idaresi ve sınıf rehber öğretmenliği duyuru, toplantı ve rehberlik bültenleri.',
    public: true,
    thumbnail_image: null,
    creation_date: '2026-09-30 10:00:00',
    update_date: '2026-10-01 10:00:00',
  },
  {
    id: 3,
    community_uuid: 'comm_genel_okul_duyurulari',
    org_id: 2,
    name: 'Atatürk Fen Lisesi Genel Duyurular & Etkinlikler',
    description: 'Tüm okul öğrenci, öğretmen ve velilerini ilgilendiren resmi duyurular, yarışmalar ve bilim şenlikleri.',
    public: true,
    thumbnail_image: null,
    creation_date: '2026-09-30 10:00:00',
    update_date: '2026-10-01 10:00:00',
  },
]

export const TURKISH_FOLDERS = [
  {
    id: 1,
    folder_uuid: 'folder_matematik_fasikulleri',
    name: '10. Sınıf Matematik MEB Uyumlu Ders Fasikülleri',
    description: 'Fonksiyonlar, paraboller ve ikinci dereceden denklemler konu özetleri ve çözümlü testler.',
    org_id: 2,
    parent_folder_uuid: null,
    creation_date: '2026-09-30 10:00:00',
    update_date: '2026-10-01 10:00:00',
    items_count: 5,
  },
  {
    id: 2,
    folder_uuid: 'folder_fizik_deney_foyleri',
    name: 'Fizik Laboratuvarı Deney Föyleri & Formül Tabloları',
    description: 'Elektrik devreleri, eşdeğer direnç ölçümleri ve manyetizma laboratuvar kılavuzları.',
    org_id: 2,
    parent_folder_uuid: null,
    creation_date: '2026-09-30 10:00:00',
    update_date: '2026-10-01 10:00:00',
    items_count: 4,
  },
  {
    id: 3,
    folder_uuid: 'folder_edebiyat_calisma_notlari',
    name: 'Divan Edebiyatı Kavram Haritaları ve Nazım Şekilleri',
    description: 'Gazel, kaside, mesnevi çözümlemeleri ve aruz kalıpları özet tabloları.',
    org_id: 2,
    parent_folder_uuid: null,
    creation_date: '2026-09-30 10:00:00',
    update_date: '2026-10-01 10:00:00',
    items_count: 6,
  },
  {
    id: 4,
    folder_uuid: 'folder_veli_rehberlik_bultenleri',
    name: 'Veli Rehberlik Bültenleri & Başarı Takip Formları',
    description: 'Ergenlik dönemi iletişimi, YKS hazırlık süreci veli rehberi ve okul-aile iş birliği kılavuzları.',
    org_id: 2,
    parent_folder_uuid: null,
    creation_date: '2026-09-30 10:00:00',
    update_date: '2026-10-01 10:00:00',
    items_count: 3,
  },
  {
    id: 5,
    folder_uuid: 'folder_biyoloji_soru_bankalari',
    name: 'Biyoloji & Kimya MEB Uyumlu Soru Bankaları',
    description: 'Hücre bölünmeleri, kalıtım ve kimyasal türler arası etkileşimler tarama testleri.',
    org_id: 2,
    parent_folder_uuid: null,
    creation_date: '2026-09-30 10:00:00',
    update_date: '2026-10-01 10:00:00',
    items_count: 5,
  },
]

export const TURKISH_COURSES = [
  {
    id: 20,
    org_id: 2,
    org_uuid: 'org_33d3ce57-c2b3-4368-aab5-840ea0e48f2e',
    course_uuid: 'course_336cd9c7-cf17-460f-b500-8474a2a6ad19',
    name: '10. Sınıf Matematik: Fonksiyonlar ve Paraboller',
    description: 'MEB 10. sınıf müfredatına tam uyumlu; fonksiyon grafikleri, parabol tepe noktası (r, k) ve simetri ekseni analizleri.',
    about: 'Bu ders 10. sınıf öğrencilerimizin analitik düşünme, parabol çizimi ve fonksiyon ilişkilerini kavramasını sağlar. Etkileşimli akıllı tahta panoları ve adım adım örneklerle desteklenmiştir.',
    learnings: 'Fonksiyon grafiğini çizme; parabol tepe noktasını bulma; simetri eksenini belirleme; teğet ve kesişim problemlerini çözme.',
    tags: 'matematik,fonksiyonlar,parabol,10.sinif',
    thumbnail_type: 'image',
    thumbnail_image: '',
    thumbnail_video: '',
    public: true,
    published: true,
    open_to_contributors: false,
    creation_date: '2026-09-30 10:00:00',
    update_date: '2026-10-01 23:52:50',
    teacher_name: 'Ahmet Yılmaz (Öğretmen)',
    authors: [
      {
        user: {
          id: 2,
          username: 'ogretmen',
          first_name: 'Ahmet',
          last_name: 'Yılmaz (Öğretmen)',
          email: 'ogretmen@oxonom.com',
          avatar_image: '',
        },
        authorship: 'CREATOR',
        authorship_status: 'ACTIVE',
      },
    ],
  },
  {
    id: 21,
    org_id: 2,
    org_uuid: 'org_33d3ce57-c2b3-4368-aab5-840ea0e48f2e',
    course_uuid: 'course_24f83958-4561-4cd5-a388-5318442304f8',
    name: '10. Sınıf Fizik: Elektrik Devreleri & Manyetizma',
    description: 'Ohm kanunu, seri ve paralel bağlı devreler, eşdeğer direnç hesaplamaları ve elektriksel güç uygulamaları.',
    about: 'Laboratuvar deney simülasyonları ile eşdeğer direnç ölçümleri, akım-gerilim ilişkisi ve Kirchhoff kanunlarının detaylı anlatımı.',
    learnings: 'Eşdeğer direnç hesaplama; akım ve gerilim dağılımını bulma; elektriksel enerji ve güç formüllerini uygulama.',
    tags: 'fizik,elektrik,devreler,10.sinif',
    thumbnail_type: 'image',
    thumbnail_image: '',
    thumbnail_video: '',
    public: true,
    published: true,
    open_to_contributors: false,
    creation_date: '2026-09-30 10:00:00',
    update_date: '2026-10-01 23:52:50',
    teacher_name: 'Ahmet Yılmaz (Öğretmen)',
    authors: [
      {
        user: {
          id: 2,
          username: 'ogretmen',
          first_name: 'Ahmet',
          last_name: 'Yılmaz (Öğretmen)',
          email: 'ogretmen@oxonom.com',
          avatar_image: '',
        },
        authorship: 'CREATOR',
        authorship_status: 'ACTIVE',
      },
    ],
  },
  {
    id: 22,
    org_id: 2,
    org_uuid: 'org_33d3ce57-c2b3-4368-aab5-840ea0e48f2e',
    course_uuid: 'course_e2c79aec-e66c-4637-b789-6934282e0135',
    name: '10. Sınıf Türk Dili ve Edebiyatı: Divan Edebiyatı',
    description: 'Divan edebiyatı nazım şekilleri (gazel, kaside, mesnevi), aruz ölçüsü, edebi sanatlar ve şairler kronolojisi.',
    about: 'Türk edebiyatının klasik dönem nazım türleri, Fuzuli, Baki, Nedim ve Şeyh Galip tahlilleri ile aruz vezni çözümlemeleri.',
    learnings: 'Gazel ve kaside beyit tahlili yapma; aruz kalıplarını tanıma; mazmun ve edebi sanatları metin üzerinde bulma.',
    tags: 'edebiyat,divan,gazel,10.sinif',
    thumbnail_type: 'image',
    thumbnail_image: '',
    thumbnail_video: '',
    public: true,
    published: true,
    open_to_contributors: false,
    creation_date: '2026-09-30 10:00:00',
    update_date: '2026-10-01 23:52:50',
    teacher_name: 'Burak Yıldız (Edebiyat Öğretmeni)',
    authors: [
      {
        user: {
          id: 2,
          username: 'ogretmen',
          first_name: 'Ahmet',
          last_name: 'Yılmaz (Öğretmen)',
          email: 'ogretmen@oxonom.com',
          avatar_image: '',
        },
        authorship: 'CREATOR',
        authorship_status: 'ACTIVE',
      },
    ],
  },
  {
    id: 23,
    org_id: 2,
    org_uuid: 'org_33d3ce57-c2b3-4368-aab5-840ea0e48f2e',
    course_uuid: 'course_efedfe1f-9fb1-4973-8fbe-b45694fda229',
    name: '10. Sınıf Biyoloji: Hücre Bölünmeleri & Kalıtım',
    description: 'Mitoz ve mayoz bölünme evreleri, eşeyli/eşeysiz üreme, Mendel ilkeleri ve genetik çaprazlama kuralları.',
    about: 'Mikroskop görüntüleri, kromozom hareketleri, crossing-over mekanizması ve soy ağacı analizi uygulamaları.',
    learnings: 'Mitoz ve mayoz aşamalarını ayırt etme; genotip ve fenotip oranlarını hesaplama; soy ağaçlarında aktarım yollarını belirleme.',
    tags: 'biyoloji,mitoz,mayoz,kalitim,10.sinif',
    thumbnail_type: 'image',
    thumbnail_image: '',
    thumbnail_video: '',
    public: true,
    published: true,
    open_to_contributors: false,
    creation_date: '2026-09-30 10:00:00',
    update_date: '2026-10-01 23:52:50',
    teacher_name: 'Ahmet Yılmaz (Öğretmen)',
    authors: [
      {
        user: {
          id: 2,
          username: 'ogretmen',
          first_name: 'Ahmet',
          last_name: 'Yılmaz (Öğretmen)',
          email: 'ogretmen@oxonom.com',
          avatar_image: '',
        },
        authorship: 'CREATOR',
        authorship_status: 'ACTIVE',
      },
    ],
  },
  {
    id: 24,
    org_id: 2,
    org_uuid: 'org_33d3ce57-c2b3-4368-aab5-840ea0e48f2e',
    course_uuid: 'course_60e7b54d-28d4-4a33-8ce4-482a2431d8dd',
    name: '10. Sınıf Kimya: Mol Kavramı ve Kimyasal Tepkimeler',
    description: 'Kimyanın temel kanunları, mol hesaplamaları, tepkime denkleştirme ve kimyasal türler arası etkileşimler.',
    about: 'Kütlenin korunumu kanunu, sabit oranlar, mol-tanecik-hacim geçişleri ve stokiyometri problemleri çözümleri.',
    learnings: 'Mol hesaplamalarını hatasız yapma; tepkime denklemlerini denkleştirme; sınırlayıcı bileşeni bularak ürün miktarını belirleme.',
    tags: 'kimya,mol,tepkimeler,10.sinif',
    thumbnail_type: 'image',
    thumbnail_image: '',
    thumbnail_video: '',
    public: true,
    published: true,
    open_to_contributors: false,
    creation_date: '2026-09-30 10:00:00',
    update_date: '2026-10-01 23:52:50',
    teacher_name: 'Ahmet Yılmaz (Öğretmen)',
    authors: [
      {
        user: {
          id: 2,
          username: 'ogretmen',
          first_name: 'Ahmet',
          last_name: 'Yılmaz (Öğretmen)',
          email: 'ogretmen@oxonom.com',
          avatar_image: '',
        },
        authorship: 'CREATOR',
        authorship_status: 'ACTIVE',
      },
    ],
  },
  {
    id: 25,
    org_id: 2,
    org_uuid: 'org_33d3ce57-c2b3-4368-aab5-840ea0e48f2e',
    course_uuid: 'course_df75f789-d935-44f9-a439-865bde8c5e34',
    name: 'Rehberlik & YKS / TYT Temel Hazırlık Kılavuzu',
    description: '10. Sınıf öğrencileri için verimli ders çalışma teknikleri, zaman yönetimi, haftalık planlama ve rehberlik kılavuzu.',
    about: 'Lise 2. sınıf düzeyinde YKS temelini sağlamlaştırma stratejileri, haftalık soru hedefi takibi ve motivasyon kılavuzu.',
    learnings: 'Haftalık ders çalışma programı hazırlama; test çözme tekniklerini geliştirme; hedef belirleme ve başarı takibi yapma.',
    tags: 'rehberlik,yks,motivasyon,planlama',
    thumbnail_type: 'image',
    thumbnail_image: '',
    thumbnail_video: '',
    public: true,
    published: true,
    open_to_contributors: false,
    creation_date: '2026-09-30 10:00:00',
    update_date: '2026-10-01 23:52:50',
    teacher_name: 'Ahmet Yılmaz (Öğretmen)',
    authors: [
      {
        user: {
          id: 2,
          username: 'ogretmen',
          first_name: 'Ahmet',
          last_name: 'Yılmaz (Öğretmen)',
          email: 'ogretmen@oxonom.com',
          avatar_image: '',
        },
        authorship: 'CREATOR',
        authorship_status: 'ACTIVE',
      },
    ],
  },
]

export const TURKISH_USERGROUPS = [
  {
    id: 6,
    usergroup_uuid: 'usergroup_10a_fen',
    name: '10-A Fen ve Matematik Şubesi',
    description: 'Rehber Öğretmen: Ahmet Yılmaz. Sayısal ağırlıklı fen ve matematik şubesi.',
    org_id: 2,
    join_code: 'OXO10A',
    grade_level: '10. Sınıf',
    mentor_teacher_name: 'Ahmet Yılmaz (Matematik)',
    mentor_teacher_email: 'ogretmen@oxonom.com',
    student_count: 6,
    boards_count: 6,
    creation_date: '2026-09-30 19:05:51',
    update_date: '2026-10-01 19:11:42',
    users: TURKISH_STUDENTS,
  },
  {
    id: 7,
    usergroup_uuid: 'usergroup_11b_sayisal',
    name: '11-B İleri Sayısal Şubesi',
    description: 'Rehber Öğretmen: Ahmet Yılmaz. İleri düzey matematik ve fizik hazırlık şubesi.',
    org_id: 2,
    join_code: 'OXO11B',
    grade_level: '11. Sınıf',
    mentor_teacher_name: 'Ahmet Yılmaz (Matematik)',
    mentor_teacher_email: 'ogretmen@oxonom.com',
    student_count: 24,
    boards_count: 4,
    creation_date: '2026-09-30 19:05:51',
    update_date: '2026-10-01 19:11:42',
    users: TURKISH_STUDENTS.slice(0, 3),
  },
  {
    id: 8,
    usergroup_uuid: 'usergroup_09c_anadolu',
    name: '9-C Anadolu Şubesi',
    description: 'Lise uyum ve temel fen-sosyal bilimler başlangıç şubesi.',
    org_id: 2,
    join_code: 'OXO09C',
    grade_level: '9. Sınıf',
    mentor_teacher_name: 'Burak Yıldız (Edebiyat)',
    mentor_teacher_email: 'burak.yildiz@oxonom.com',
    student_count: 28,
    boards_count: 3,
    creation_date: '2026-09-30 19:05:51',
    update_date: '2026-10-01 19:11:42',
    users: TURKISH_STUDENTS.slice(3),
  },
  {
    id: 17,
    usergroup_uuid: 'usergroup_10a_fen_default',
    name: '10-A Fen ve Matematik Şubesi',
    description: 'Rehber Öğretmen: Ahmet Yılmaz. Sayısal ağırlıklı fen ve matematik şubesi.',
    org_id: 1,
    join_code: 'OXO10A',
    grade_level: '10. Sınıf',
    mentor_teacher_name: 'Ahmet Yılmaz (Matematik)',
    mentor_teacher_email: 'ogretmen@oxonom.com',
    student_count: 6,
    boards_count: 6,
    creation_date: '2026-09-30 19:05:51',
    update_date: '2026-10-01 19:11:42',
    users: TURKISH_STUDENTS,
  },
  {
    id: 18,
    usergroup_uuid: 'usergroup_11b_sayisal_default',
    name: '11-B İleri Sayısal Şubesi',
    description: 'Rehber Öğretmen: Ahmet Yılmaz. İleri düzey matematik ve fizik hazırlık şubesi.',
    org_id: 1,
    join_code: 'OXO11B',
    grade_level: '11. Sınıf',
    mentor_teacher_name: 'Ahmet Yılmaz (Matematik)',
    mentor_teacher_email: 'ogretmen@oxonom.com',
    student_count: 24,
    boards_count: 4,
    creation_date: '2026-09-30 19:05:51',
    update_date: '2026-10-01 19:11:42',
    users: TURKISH_STUDENTS.slice(0, 3),
  },
  {
    id: 19,
    usergroup_uuid: 'usergroup_09c_anadolu_default',
    name: '9-C Anadolu Şubesi',
    description: 'Lise uyum ve temel fen-sosyal bilimler başlangıç şubesi.',
    org_id: 1,
    join_code: 'OXO09C',
    grade_level: '9. Sınıf',
    mentor_teacher_name: 'Burak Yıldız (Edebiyat)',
    mentor_teacher_email: 'burak.yildiz@oxonom.com',
    student_count: 28,
    boards_count: 3,
    creation_date: '2026-09-30 19:05:51',
    update_date: '2026-10-01 19:11:42',
    users: TURKISH_STUDENTS.slice(3),
  },
]
